"""Markdown knowledge-base generation for catalog entries."""

from __future__ import annotations

from pathlib import Path

from samaj.tools.catalog import ToolCatalogEntry


def render_tool_markdown(entry: ToolCatalogEntry) -> str:
    return "\n".join(
        (
            f"# {entry.tool_name}",
            "",
            "Verification status: Unknown / Not verified",
            "Source: user-pasted tool inventory",
            "Generated by AI: yes",
            "Needs manual review: yes",
            "Confidence level: unknown",
            "",
            f"Category: {entry.category}",
            f"Subcategory: {entry.subcategory or 'Unknown / Not verified'}",
            f"Catalog status: {entry.catalog_status}",
            f"Support status: {entry.support_status}",
            "",
            "Tool Catalog entry does not mean tool support, endorsement, "
            "verification, safety, installation, execution, recommendation, "
            "operational support, or permission to use.",
            "",
            "What is this tool?",
            entry.description,
            "",
            "Supported OS: Unknown / Not verified",
            f"Windows install notes: {entry.install_method_windows}",
            f"Kali install notes: {entry.install_method_kali}",
            f"Linux install notes: {entry.install_method_linux}",
            "",
            f"Safety note: {entry.safety_note}",
            f"License note: {entry.license_note}",
            f"Official URL: {entry.official_url or 'Unknown / Not verified'}",
            f"Documentation URL: {entry.documentation_url or 'Unknown / Not verified'}",
        )
    )


def write_tool_markdown(entry: ToolCatalogEntry, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_name = "".join(ch if ch.isalnum() else "-" for ch in entry.tool_name).strip("-")
    path = output_dir / f"{entry.sequence:04d}-{safe_name[:80]}.md"
    path.write_text(render_tool_markdown(entry), encoding="utf-8")
    return path
